### ISSUE TITLE
Question: How to run tests 

### ISSUE THREAD

**Issue by shark8me** [DEX-Company/starfish-py#105]
The docs specify 2 ways to run tests:

- `python3 -m pytest tests` in [shrimp](https://shrimp.octet.services/starfish/starfish-py/latest/getting_started.html#run-the-unit-tests)
- `python3 setup.py test` in the starfish readme. 

Are both equivalent?

**Comment by tmarble** [comment]
The answer is that because we are running in a venv these are equivalent.

FFI please see:
* https://docs.pytest.org/en/latest/goodpractices.html
* https://tox.readthedocs.io/en/latest/example/pytest.html

I also create a PR to harmonize the docs on this:
https://github.com/DEX-Company/starfish-py/pull/108
